FROM jenkins/jenkins:lts-jdk17

// налаштування образу дженкінс та встановлення всього для роботи із Докером

USER root

RUN apt-get update && \
    apt-get install -y docker.io curl && \
    mkdir -p /usr/libexec/docker/cli-plugins && \
    curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/libexec/docker/cli-plugins/docker-compose && \
    chmod +x /usr/libexec/docker/cli-plugins/docker-compose

RUN usermod -aG docker jenkins

USER jenkins