FROM jenkins/jenkins:lts-jdk17

USER root

# Устанавливаем Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Разрешить Jenkins работать с Docker socket
RUN usermod -aG docker jenkins

USER jenkins